#if !defined(META_TYPES_H)
#define META_TYPES_H
#include "type_info.h"
// generated by type_metadata.c:886
typedef unsigned char u8;

typedef signed char s8;

typedef unsigned short u16;

typedef signed short s16;

typedef unsigned int u32;

typedef signed int s32;

typedef float f32;

typedef double f64;

enum States : u32
{
	IDLE = 0,
	RUNNING = 1,
	LOADING = 2,
	FINISHED = 3,
};

struct Vector2
{
	f32 x;
	f32 y;
};

struct Circle
{
	f32 r;
	Vector2 pos;
};

struct RoundedSegment
{
	f32 r;
	Vector2 p1;
	Vector2 p2;
};

struct RoundedPolygon
{
	f32 r;
	u32 count;
	Vector2 *p;
};

enum Shape : u32
{
	Circle = 1,
	Segment = 2,
	Triangle = 3,
};


// generated by type_metadata.c:985
TypeInfo* type_info_from_shape(Shape v);
u32 max_slot_from_shape(Shape v);

// generated by type_metadata.c:1008
extern TypeInfo u8_type_info;
extern TypeInfo s8_type_info;
extern TypeInfo u16_type_info;
extern TypeInfo s16_type_info;
extern TypeInfo u32_type_info;
extern TypeInfo s32_type_info;
extern TypeInfo f32_type_info;
extern TypeInfo f64_type_info;
extern TypeInfo States_type_info;
extern TypeInfo Vector2_type_info;
extern TypeInfo Circle_type_info;
extern TypeInfo RoundedSegment_type_info;
extern TypeInfo RoundedPolygon_type_info;
extern TypeInfo Shape_type_info;

#endif // META_TYPES_H
