#include "meta_types.h"
#include "type_info.h"
// generated by type_metadata.cpp:1063
TypeInfoMember Vector2_members[0] = {
};
TypeInfoMember Circle_members[0] = {
};
TypeInfoMember RoundedSegment_members[0] = {
};
TypeInfoMember RoundedPolygon_members[0] = {
};

// generated by type_metadata.cpp:1102
TypeInfoEnumerant States_members[4] = {
	{"IDLE", 4, 0},
	{"RUNNING", 7, 1},
	{"LOADING", 7, 2},
	{"FINISHED", 8, 3},
};
TypeInfoEnumerant Shape_members[3] = {
	{"Circle", 6, 1},
	{"Segment", 7, 2},
	{"Triangle", 8, 3},
};

// generated by type_metadata.cpp:1138
TypeInfo States_type_info = {TypeKind_Enum, "States", 6, 4, States_members, 0};
TypeInfo Vector2_type_info = {TypeKind_Struct, "Vector2", 7, 0, Vector2_members, 0};
TypeInfo Circle_type_info = {TypeKind_Struct, "Circle", 6, 0, Circle_members, 0};
TypeInfo RoundedSegment_type_info = {TypeKind_Struct, "RoundedSegment", 14, 0, RoundedSegment_members, 0};
TypeInfo RoundedPolygon_type_info = {TypeKind_Struct, "RoundedPolygon", 14, 0, RoundedPolygon_members, 0};
TypeInfo Shape_type_info = {TypeKind_Enum, "Shape", 5, 3, Shape_members, 0};

// generated by type_metadata.cpp:1198
TypeInfo*
type_info_from_shape(Shape v)
{
TypeInfo* result;
switch (v)
{
default:
{
result = 0;
}break;
case Circle:
{
result = &Circle_type_info;
}break;
case Segment:
{
result = &RoundedSegment_type_info;
}break;
case Triangle:
{
result = &RoundedPolygon_type_info;
}break;
}
return(result);
}

