#include "meta_types.h"
// generated by type_metadata.c:1024
TypeInfoMember Vector2_members[2] = {
	{"x", 1, -1, &f32_type_info},
	{"y", 1, -1, &f32_type_info},
};
TypeInfoMember Circle_members[2] = {
	{"r", 1, -1, &f32_type_info},
	{"pos", 3, -1, &Vector2_type_info},
};
TypeInfoMember RoundedSegment_members[3] = {
	{"r", 1, -1, &f32_type_info},
	{"p1", 2, -1, &Vector2_type_info},
	{"p2", 2, -1, &Vector2_type_info},
};
TypeInfoMember RoundedPolygon_members[3] = {
	{"r", 1, -1, &f32_type_info},
	{"count", 5, -1, &u32_type_info},
	{"p", 1, 1, &Vector2_type_info},
};

// generated by type_metadata.c:1063
TypeInfoEnumerant States_members[4] = {
	{"IDLE", 4, 0},
	{"RUNNING", 7, 1},
	{"LOADING", 7, 2},
	{"FINISHED", 8, 3},
};
TypeInfoEnumerant Shape_members[3] = {
	{"Circle", 6, 1},
	{"Segment", 7, 2},
	{"Triangle", 8, 3},
};

// generated by type_metadata.c:1099
TypeInfo u8_type_info = {TypeKind_Basic, "u8", 2, 1, 0, 0};
TypeInfo s8_type_info = {TypeKind_Basic, "s8", 2, 1, 0, 0};
TypeInfo u16_type_info = {TypeKind_Basic, "u16", 3, 2, 0, 0};
TypeInfo s16_type_info = {TypeKind_Basic, "s16", 3, 2, 0, 0};
TypeInfo u32_type_info = {TypeKind_Basic, "u32", 3, 4, 0, 0};
TypeInfo s32_type_info = {TypeKind_Basic, "s32", 3, 4, 0, 0};
TypeInfo f32_type_info = {TypeKind_Basic, "f32", 3, 4, 0, 0};
TypeInfo f64_type_info = {TypeKind_Basic, "f64", 3, 8, 0, 0};
TypeInfo States_type_info = {TypeKind_Enum, "States", 6, 4, States_members, &u32_type_info};
TypeInfo Vector2_type_info = {TypeKind_Struct, "Vector2", 7, 2, Vector2_members, 0};
TypeInfo Circle_type_info = {TypeKind_Struct, "Circle", 6, 2, Circle_members, 0};
TypeInfo RoundedSegment_type_info = {TypeKind_Struct, "RoundedSegment", 14, 3, RoundedSegment_members, 0};
TypeInfo RoundedPolygon_type_info = {TypeKind_Struct, "RoundedPolygon", 14, 3, RoundedPolygon_members, 0};
TypeInfo Shape_type_info = {TypeKind_Enum, "Shape", 5, 3, Shape_members, &u32_type_info};

// generated by type_metadata.c:1159
TypeInfo*
type_info_from_shape(Shape v)
{
TypeInfo* result;
switch (v)
{
default:
{
result = 0;
}break;
case Circle:
{
result = &Circle_type_info;
}break;
case Segment:
{
result = &RoundedSegment_type_info;
}break;
case Triangle:
{
result = &RoundedPolygon_type_info;
}break;
}
return(result);
}
u32
max_slot_from_shape(Shape v)
{
u32 result;
switch (v)
{
default:
{
result = 0;
}break;
case Circle:
case Segment:
{
result = 64;
}break;
case Triangle:
{
result = 12;
}break;
}
return(result);
}

