#if !defined(METATYPES_H)
#define METATYPES_H
// generated by type_metadata.cpp:909
#include "pch.h"
// generated by type_metadata.cpp:925
enum States : int
{
	IDLE = 0,
	RUNNING = 1,
	LOADING = 2,
	FINISHED = 3,
};

struct Vector2
{
};

struct Circle
{
};

struct RoundedSegment
{
};

struct RoundedPolygon
{
};

enum Shape : int
{
	Circle = 1,
	Segment = 2,
	Triangle = 3,
};


struct TypeInfo;
// generated by type_metadata.cpp:1024
TypeInfo* type_info_from_shape(Shape v);

// generated by type_metadata.cpp:1047
extern TypeInfo States_type_info;
extern TypeInfo Vector2_type_info;
extern TypeInfo Circle_type_info;
extern TypeInfo RoundedSegment_type_info;
extern TypeInfo RoundedPolygon_type_info;
extern TypeInfo Shape_type_info;

#endif // METATYPES_H
