name: windows-ci
on:
  pull_request:
  push:
    branches:
      - main
      - master

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10' 
    - run: python build.py regen && python build.py norun
    - uses: actions/upload-artifact@v3
      with:
        name: build
        path: PartOfThePack.exe


  upload:
    if: "contains(github.event.head_commit.message, '!BUILD')"
    runs-on: ubuntu-latest
    needs:
      - build-windows
    steps:
    - uses: actions/checkout@v3
    - name: Download all artifacts
      uses: actions/download-artifact@v2

    - name: prepare zip
      run: |
        cp build/PartOfThePack.exe PartOfThePack.exe
        zip -r PartOfThePack.zip PartOfThePack.exe res/potp res/shaders
    
    - name: Upload binary
      uses: actions/upload-artifact@v2
      with:
        name: windows-release
        path: PartOfThePack.zip
  
    - name: Update Release
      uses: meeDamian/github-release@2.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        prerelease: true
        allow_override: true
        gzip: folders
        tag: windows-master
        name: windows-master
        body: Build of PartOfThePack from master.
        files: >
          PartOfThePack.zip