name: mac-ci
on:
  pull_request:
  push:
    branches:
      - main
      - master

jobs:
  build-mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10' 
    - run: python build.py regen && python build.py norun
    - uses: actions/upload-artifact@v3
      with:
        name: build
        path: app.out

  upload:
    runs-on: ubuntu-latest
    needs:
      - build-mac
    steps:
    - uses: actions/checkout@v3
    - name: Download all artifacts
      uses: actions/download-artifact@v2

    - name: prepare zip
      run: |
        cp build/app.out app.out
        zip -r PartOfThePack.zip app.out res/potp res/shaders
    
    - name: Upload binary
      uses: actions/upload-artifact@v2
      with:
        name: release
        path: PartOfThePack.zip
  
