name: linux-ci
on:
  pull_request:
  push:
    branches:
      - main
      - master

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: install deps
      run: |
        sudo apt-get install -y --no-install-recommends libglfw3 libglfw3-dev libx11-dev libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev libxext-dev libxfixes-dev
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10' 
    - run: python build.py regen && python build.py norun
    - uses: actions/upload-artifact@v3
      with:
        name: build
        path: app.out
